### ISSUE TITLE
HTML in PHP doc and scss hinting/completion not working

### ISSUE THREAD

**Issue by tomliv** [emmetio/nova-plugin#6]
HTML in a PHP doc:
![nove-codehinting-html](https://user-images.githubusercontent.com/1153953/82942226-a52e2700-9f65-11ea-914f-9a72111086f5.gif)

scss file:
![nova-codehint](https://user-images.githubusercontent.com/1153953/82942243-ac553500-9f65-11ea-964f-3319305ea5de.gif)

**Comment by sergeche** [comment]
Should be fixed in v1.2.0

**Comment by tomliv** [comment]
I am still seeing issues in scss files (attached) and html in php files is spotty.

![CleanShot 2020-05-29 at 14 04 45](https://user-images.githubusercontent.com/1153953/83291124-d43ad780-a1b5-11ea-99bf-6965bb5a448c.gif)
