### ISSUE TITLE
Unexpected character creation in CSS files

### ISSUE THREAD

**Issue by blackboxideas** [emmetio/nova-plugin#7]
When creating a CSS class, if I use autocomplete on any of the items when the style properties are on new lines an unexpected character error is reported.

![css-emmet](https://user-images.githubusercontent.com/6748783/83073801-f5da7880-a068-11ea-818f-c6d769e707ec.gif)

**Comment by sergeche** [comment]
What Emmet version you’re using?

**Comment by blackboxideas** [comment]
This is the plugin version 1.2.0. 
The error is being reported by the CSS Validator extension, so it may be how that is interpreting things when combined with the emmet extension?

Slightly odd - entering a new line will remove the error.

**Comment by sergeche** [comment]
Emmet also adds hints to captured abbreviations. I’ve fixed issue when expanded abbreviation is reported as invalid Emmet abbreviation, but issue dot mark seems to be related to other extension, not Emmet

**Comment by sergeche** [comment]
Do you still experience any issues with this?

**Comment by blackboxideas** [comment]
Just to confirm - I'm still seeing this. However, I'll raise the issue over on the Panic / Nova issues page.

**Comment by blackboxideas** [comment]
@sergeche - just for reference: https://dev.panic.com/panic/nova-issues/-/issues/1031

**Comment by sergeche** [comment]
On screenshot in https://dev.panic.com/panic/nova-issues/-/issues/1031, it definitely looks like Emmet error, yet I can’t reproduce it. Can you record video how you get this error?

**Comment by blackboxideas** [comment]
Sure, here's a .gif of me typing some CSS. I've disabled the CSS Validator / HTML Validator - so this appears to be the Emmet plugin reporting the error.

Once you create a new line or close/open the file the error vanishes. 
![ezgif-3-ec007bf6b15d](https://user-images.githubusercontent.com/6748783/85182381-664b7280-b280-11ea-9596-f85b731a31bc.gif)

**Comment by sergeche** [comment]
Should be fixed in v1.2.2
